import Head from "next/head";
import Image from "next/image";
import Login from "../components/login";
import styles from "../styles/Home.module.css";
import { useMoralis } from "react-moralis";
import Header from "../components/Header";
import Message from "../components/Message";

export default function Home() {
  // const isAuthenticated = false;
  const { isAuthenticated, logout } = useMoralis();
  //  console.log('Hello welcome to Index .js')
  if (!isAuthenticated) return <Login />;

  return (
    <div className="h-screen overflow-y-scroll bg-gradient-to-b from-black to-fuchsia-900">
      <Head>
        <title>Metaverse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

    
      <div className="max-w-screen-2xl  mx-auto">

      <Header/>
     <Message/>
      
      </div>
      {/* Footer */}
      {/* <button onClick={logout}>Logout</button> */}
    </div>
  );
}
