import Head from "next/head";
import Image from "next/image";
import Login from "../components/login";
import styles from "../styles/Home.module.css";
import { useMoralis } from "react-moralis";

export default function Home() {
  // const isAuthenticated = false;
  const { isAuthenticated , logout} = useMoralis();
//  console.log('Hello welcome to Index .js')
  if (!isAuthenticated) return <Login />;
 
    return (
      <div className="h-screen">
        <Head>
          <title>Metaverse</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Hello Welcome</h1>
        <button onClick={logout}>Logout</button>
      </div>
    );
}
